### ISSUE TITLE
Ability to specify voice_id

### ISSUE THREAD

**Issue by danblah** [carleeno/elevenlabs_tts#1]
I'd like the ability to specify the unique voice_id over just name. This would allow for use of their voicelab voices (ie clones of my own voice). Specifying a user-generated name now results in a generation using the default name.

See https://api.elevenlabs.io/docs#/voices/Get_voices_v1_voices_get

Love this btw. Thanks for making it.

**Comment by carleeno** [comment]
Absolutely, I was considering adding both but by specifying a name for one of my custom voices (in my case Heather) I was able to use the custom voice. Is that not working for you? Or is the issue that you have more than 1 voice with the same name?

Currently what we do is fetch a list of all your voices and pick the voice_id where the name you provide matches the names in the list. It must be an exact match or it defaults to Domi, you can check the log for warnings to see if it's not finding your custom voice by name.

**Comment by carleeno** [comment]
Oh, if you created the custom voice after setting up the integration then the cached list of your voices wouldn't include the new one, possibly explaining why it wouldn't have worked with your custom voice by name.

I'll add some logic to refetch the list if it can't find a voice by name, as well as add the option to use the id instead for those who prefer that.

**Comment by danblah** [comment]
Ahhh, that's exactly what the issue is! Thank you!
