### ISSUE TITLE
Support for legacy voices.

### ISSUE THREAD

**Issue by patrik-malina** [carleeno/elevenlabs_tts#140]
### System Health details

/

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I'm having problem using legacy voices. Used Jeremy voice:

`Could not find voice with name {}, available voices: ['Sarah', 'Laura', 'Charlie', 'George', 'Callum', 'Liam', 'Charlotte', 'Alice', 'Matilda', 'Will', 'Jessica', 'Eric', 'Chris', 'Brian', 'Daniel', 'Lily', 'Bill']`

I thing this need to implement in code (i'm not coder):
`curl --request GET \
  --url 'https://api.elevenlabs.io/v1/voices?show_legacy=true'`

### Reproduction steps

/

### Debug logs

```text
/
```

**Comment by patrik-malina** [comment]
Actually I did it :)

But it can be done more elegant, with say option for legacy voices in config.

How is done:
changed file elevenlabs.py in line 95 to:
`endpoint = "voices?show_legacy=true"`
restarted HA and mine favorite voice is back again :)

**Comment by carleeno** [comment]
@patrik-malina thanks
Looking into it, it doesn't seem that there's a good way to get the config options during the stage where it fetches the list of voices....so I think we'll just have to turn it on for all, and maybe append `(Legacy)` to the name to differentiate them. But changing the names like that will also break user configs that already have a legacy voice set. Although I suspect since it's already broken it's not a big deal to change it. What do you think?

**Comment by carleeno** [comment]
@patrik-malina I think I found a non-breaking way to add support for legacy with the " (Legacy)" suffix...

Can you give this prerelease a try?
https://github.com/carleeno/elevenlabs_tts/releases/tag/2.4.0-pre.1

It should show the (Legacy) suffix next to the old voices, and selecting them that way (with the suffix) should work, as well as specifying the name without the suffix directly in config should work as well.

This also updates the default model, feel free to give that a try as well to see if it's faster.

**Comment by patrik-malina** [comment]
@carleeno Can confirm, that this works. Thank you.
