### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by collateral87** [carleeno/elevenlabs_tts#3]
Elevenlabs published their multilingual option aside their mono english models.
Does this awsome Integration supports this Feature?

**Comment by carleeno** [comment]
Ooh it looks like they recently added a lot of cool new features. I'll work on updating it this weekend to take advantage of the new parameters.

**Comment by carleeno** [comment]
After updating you'll need to set in the `model` param in your configuration.yaml, as I left the default as monolingual to match elevenlab's default behavior.
