### ISSUE TITLE
Request for Full Multi language support

### ISSUE THREAD

**Issue by saya6k** [carleeno/elevenlabs_tts#72]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I can use this TTS as English, French, Spanish, German etc in Home Assistant Voice Assistant. But it does not work on some other languages like Japanese, Korean, Chinese. ElevenLabs supports these languages too.

### Describe the solution you'd like

Try and make it work with all languages ElevenLabs support.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by carleeno** [comment]
@saya6k sorry for the delay on this.

I just created a pre-release (2.3.0-pre.1) with the extra languages added as I'm currently on extended travel and I don't have a way to test it in HA. You can use [this guide](https://hacs.xyz/docs/faq/select_version/) to manually select this pre-release to try it out, and let me know if it works for you!

**Comment by saya6k** [comment]
It's working. I have tested on Korean and Japanese. Thanks.
