### ISSUE TITLE
language

### ISSUE THREAD

**Issue by mortalone** [carleeno/elevenlabs_tts#85]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

i sould like to be able to change language

### Describe the solution you'd like

Hi. im just wondering if it would be possible to set the language ?

### Describe alternatives you've considered

.

### Additional context

.

**Comment by carleeno** [comment]
Hi @mortalone, it should speak any of the supported languages when you provide text in that language. Make sure you configured it to use a multilingual model v1 or v2 (see readme for example) and for best results, use a voice built on the selected model.

If you're using it as your Assist's voice, you'll need to change your HA language to get Assist to speak in that language.
